### ISSUE TITLE
Remove custom user system and allow intergrations with 3rd party identity providers

### ISSUE THREAD

**Issue by ben-ryder** [ben-ryder/local-first-backend#2]
Inspired by [Platformatic's approach](https://oss.platformatic.dev/docs/reference/db/authorization/introduction) to users and authentication, rather than writing and maintaining a custom user management and auth system just offer the functionality to integrate with 3rd party providers like Auth0.

This integration should either be generic enough to allow more than one provider, or it should focus on an open source and self-hostable user management/auth system like super tokens or similar.

**Comment by Ben-Ryder** [comment]
## Proposal
Here is a high level proposal of what I think this system should be, at least at the moment for v1 functionality.

### Authentication and Authorization
All user storage and authentication functionality will now be left up to a thrid pary provider. Requests to the server or websockets should include a JWT access token that's been created by the provider. The server can then use a JWKS endpoint or shared secret to verify that token. This token should include some sort of user ID (for example in the `sub` claim) which the server can then use to link up server data like changes or profiles to the correct user.

![lfb-auth-flow](https://user-images.githubusercontent.com/35773406/200620837-3b34750c-4040-40d0-ba1a-56817b635762.png)
*Diagram is only an example, the exact flow between an app and the auth provider may vary and doesn't really concern the LFB application.

#### Future Improvements
Right now there is no need to implement roles or advanced access control as the LFB server is just a basic store of data. In the future this could maybe be implemented by expecting a `roles` or `scopes` claim within the token, which just stores what roles the user has as strings like `"roles": ["user", "editor"]`.

#### Configuration and Environment Changes
By default I think the system should probably get the "user ID" value from the `sub` claim in the token if it exists, but configuration could allow customisation. For example, if the token includes a user object payload you might set `AUTH_TOKEN_USER_ID_KEY="user.id"`.

This could also be expanded to the roles claim in the future too, for example `AUTH_TOKEN_USER_ROLES_KEY="user.roles"`.

**TODO**: should the system support getting the user ID and other data from an ID token supplied in the access token, rather than directly as a claim in the token itself? This may allow easier usage with providers using OIDC.

### Database Changes
I will replace the `users` table with a `profiles` table which just contains a `user_id STRING` column and a `data JSONB` column.
This will allow the toolkit to store the encryption secret it needs to do client side encryption and is also flexible enough to allow for further expansion or custom usage by applications such as storing user preferences etc.

The `changes` table will still have it's own `user_id` column but this will also just be a `user_id STRING` column and won't be a foreign key. The `changes` and `profiles` tables will not have any relationship.

### API Changes
#### `/auth`
All auth endpoints and related functionality will be deleted as this won't be needed anymore.

#### `/users`
Relevant `/users` endpoints can be converted to `/profile`.

**Comment by Ben-Ryder** [comment]
I implemented this, now I've 180'ed and reverted these changes.  
While in theory not building my own user/auth system is good, this change would mean that anyone wanting to self-host the server would need to also self-host their own Logto instance and their own front-end.
It was also making the front-end logic and processing pretty complex as there was effectively two different user stores.

Keeping the built-in user & auth system will make hosting much easier, and although it will increase the maintenance burden I think in the long run it will make things easier as everything is interconnected and I can build user/auth opinions into the toolkit as well.

**Comment by ben-ryder** [comment]
When I looked into Logto initially it didn't have RBAC so wasn't a usable option to invest in for my apps, however with its v1.0 release it now has this feature among other improvements and although my concerns above about hosting & processing complexity are still valid, I want to maintain as little code as possible.

**Comment by ben-ryder** [comment]
this has now been implemented
